on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.7, 1.17.4]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: go test -v ./...
      - uses: dominikh/staticcheck-action@v1.0.0
        with:
          version: "2021.1.1"
          install-go: false
          cache-key: ${{ matrix.go }}
      - name: Vet
        run: go vet -v ./...
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...