on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.7, 1.17.4]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Install Tools
        run: |
          go get -u honnef.co/go/tools/cmd/staticcheck@latest
          go get -u github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Test
        run: go test -v ./...
      - name: Static Check
        run: staticcheck ./...
      - name: Vet
        run: go vet -v ./...
      - name: Secure
        run: gosec ./...